# Generated by Django 5.2.16 on 2026-08-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 1)), name='detallepedido_cantidad_minima'),
        ),
    ]
