# Generated by Django 5.2.16 on 2026-08-07 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('DANADO', 'El producto llegó dañado'), ('EQUIVOCADO', 'Me enviaron un producto distinto'), ('NO_CORRESPONDE', 'No corresponde a la descripción'), ('OTRO', 'Otro motivo')], max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='SOLICITADA', max_length=20)),
                ('respuesta', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('detalle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devolucion', to='pedidos.detallepedido')),
            ],
            options={
                'verbose_name': 'devolución',
                'verbose_name_plural': 'devoluciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
