# Generated by Django 5.2.16 on 2026-08-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tarjeta_final',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tarjeta_marca',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
