# Generated by Django 5.2.16 on 2026-08-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_direccion_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
